version: '3.3'
services:
  mysql_recover:
    build: .
    image: mysql_recover
    container_name: mysql_recover
    volumes:
      - ./recover.sh:/recover.sh
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"